# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9e743553d7182816b5577a5ea0c66b08b90fee82f80f443e48bf8222de2d9a5dd37de1f07dbaf01b5be43f39d55171e6036030b4646ca2a10304a7ddc7c6d1d8

test:
  secret_key_base: ac19bea73d828767ea857473fc3303ad116f27da1a90a3aabe64e8f93d84b6f4ddc1f7bc795efefcc7bf0d840d21fbccfc4281dfb946c2a513ccd929e01f40a3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
